version: 2
jobs:
  build:
    working_directory: /go/src/github.com/larse514/gohelloworldservicecontainer
    docker:
      - image: larse514/circleci-golang:latest
    environment:
      TEST_RESULTS: /tmp/test-results
      IMAGE: hello
    steps:
    - checkout
    - run: mkdir -p $TEST_RESULTS
    - run: sudo service docker start
    - restore_cache:
        keys:
          - v1-pkg-cache
    - run: go get github.com/jstemmer/go-junit-report

    - run:
        name: Run unit tests
        # environment:
        #   CONTACTS_DB_URL: "postgres://circleci-demo-go@localhost:5432/circle_test?sslmode=disable"
        #   CONTACTS_DB_MIGRATIONS: /go/src/github.com/CircleCI-Public/circleci-demo-go/db/migrations
        command: |
          trap "go-junit-report <${TEST_RESULTS}/go-test.out > ${TEST_RESULTS}/go-test-report.xml" EXIT
          make test | tee ${TEST_RESULTS}/go-test.out
    - run: make TAG="${IMAGE}:0.0.${CIRCLE_BUILD_NUM}"
    - run:
        name: Run integration tests
        command: |
          make run
          curl --fail http://localhost:8080

    - save_cache:
        key: v1-pkg-cache
        paths:
          - "/go/pkg"

    - store_artifacts:
        path: /tmp/test-results
        destination: raw-test-output

    - store_test_results:
        path: /tmp/test-results